#!/usr/bin/env ruby
# frozen_string_literal: true

# A polycubing@home volunteer client. Usage:
#   script/at_home/client --name laptop [--give-up-after SECONDS] [--url http://host:9292] [--limit N] [--once]
#
# Holds no census state: leases a unit, solves it locally, returns the answer.
# Everything it returns is re-verified by the coordinator.

require_relative "../../lib/census"

arguments = ARGV.dup

def option(arguments, flag, default)
  return default unless (position = arguments.index(flag))

  arguments.delete_at(position)
  arguments.delete_at(position)
end

def flag?(arguments, flag)
  return false unless (position = arguments.index(flag))

  arguments.delete_at(position)
  true
end

require "socket"
handle = option(arguments, "--handle", "worker-#{Socket.gethostname}-#{Process.pid}")
display_name = option(arguments, "--name", nil)
url = option(arguments, "--url", ENV.fetch("POLYCUBE_AT_HOME", "http://127.0.0.1:9292"))
contact = option(arguments, "--contact", nil)
limit = option(arguments, "--limit", nil)&.then { Integer(it) }
once = flag?(arguments, "--once")
give_up_after = option(arguments, "--give-up-after", nil)&.then { Integer(it) }

client = Census::AtHome::Client.new(url:, handle:, display_name:, contact:, give_up_after:,
                                    report: ->(line) { puts "#{Time.now.utc.iso8601}  #{line}" })
tally = begin
  client.run(limit:, once:)
rescue Interrupt
  puts "\nstopped by request"
  {}
end
puts "done: #{tally.sort.to_h.inspect}"
